pipeline:
  build:
    image: maven:3.3.3-jdk-8-onbuild
    pull: true
    commands:
      - mvn clean install -Dmaven.test.skip=true
      - sleep 60
      
  slack:
    image: plugins/slack
    channel: water-pipe
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
