pipeline:
  build:
    image: maven:3.3.3-jdk-8-onbuild
    pull: true
    commands:
      - mvn clean install -Dmaven.test.skip=true
      - sleep 10

  slack:
    image: plugins/slack
    channel: water-pipe
    secrets: [ slack_webhook ]
    image_url: https://unsplash.it/256/256/?random
    icon_url: https://unsplash.it/256/256/?random
    template: >
     {{#success build.status}}
       build {{build.number}} succeeded. Good job.
     {{else}}
       build {{build.number}} failed. Fix me please.
     {{/success}}
    when:
      status: [ success, failure ]
