pipeline:
  build:
    image: maven:3.3.3-jdk-8-onbuild
    pull: true
    commands:
      - mvn clean install -Dmaven.test.skip=true
      - sleep 10
      
  slack:
    image: plugins/slack
    channel: water-pipe
    webhook: https://hooks.slack.com/services/...
    when:
      status: [ success, failure ]
